// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA9saywmj3HuI7TuZk1rfyRUb1gLkr9Mc',
    appId: '1:321840787253:web:a9398d0fac268a6489667c',
    messagingSenderId: '321840787253',
    projectId: 'hackathon-3b0db',
    authDomain: 'hackathon-3b0db.firebaseapp.com',
    storageBucket: 'hackathon-3b0db.appspot.com',
    measurementId: 'G-Q5KD2WZK1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1eAxU4r16rFNYApoE-XKB9952KNe8Jko',
    appId: '1:321840787253:android:34b52fbb6d9a7c4b89667c',
    messagingSenderId: '321840787253',
    projectId: 'hackathon-3b0db',
    storageBucket: 'hackathon-3b0db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhm4IPHusbwkFLxSIhW2GzyRlvBWc9HoA',
    appId: '1:321840787253:ios:807979035061a94889667c',
    messagingSenderId: '321840787253',
    projectId: 'hackathon-3b0db',
    storageBucket: 'hackathon-3b0db.appspot.com',
    iosClientId: '321840787253-aqjjtn8ntge1gnlji9vaivj8b9v3bto0.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathanon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhm4IPHusbwkFLxSIhW2GzyRlvBWc9HoA',
    appId: '1:321840787253:ios:807979035061a94889667c',
    messagingSenderId: '321840787253',
    projectId: 'hackathon-3b0db',
    storageBucket: 'hackathon-3b0db.appspot.com',
    iosClientId: '321840787253-aqjjtn8ntge1gnlji9vaivj8b9v3bto0.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathanon',
  );
}
